version: "3.4"

services:
  identifier:
    restart: "no"
    ports:
      - "80:80"
  dispatcher:
    restart: "no"
  database:
    restart: "no"
  virtuoso:
    ports:
      - "8890:8890"
    restart: "no"
  resource:
    restart: "no"
  cache:
    restart: "no"
  mocklogin:
    image: lblod/mock-login-service:latest
    links:
      - database:database
    restart: "no"
  adressenregister:
    restart: "no"
  jobs-controller:
    restart: "no"
  delta-producer-background-initiator:
    environment:
        CRON_PATTERN_DUMP_JOB: "0 0 * * *" # Midnight. Effectively off
        CRON_PATTERN_HEALING_JOB: "0 0 * * *" # Midnight. Effectively off
        START_INITIAL_SYNC: "false"
    restart: "no"
  delta-producer-pub-graph-maintainer-contactdata:
    restart: "no"
  delta-producer-dump-file-publisher:
    restart: "no"
  file:
    restart: "no"
  delta-notifier:
    restart: "no"

