version: "3.4"

services:
  identifier:
    restart: "no"
    ports:
      - "80:80"
  dispatcher:
    restart: "no"
  database:
    ports:
      - "8890:8890"
    restart: "no"
  database:
    restart: "no"
  resource:
    restart: "no"
  cache:
    restart: "no"