version: "3.4"

services:
  project-scripts:
    restart: "no"
  frontend:
    restart: "no"
  identifier:
    restart: "no"
    ports:
      - "80:80"
  accountdetail:
    restart: "no"
  dispatcher:
    restart: "no"
  database:
    restart: "no"
  virtuoso:
    restart: "no"
    ports:
      - "8890:8890"
  resource:
    restart: "no"
  cache:
    restart: "no"
  migrations:
    restart: "no"
  login:
    restart: "no"
  update-bestuurseenheid-mock-login:
    restart: "no"
  mocklogin:
    image: lblod/mock-login-service:latest
    restart: "no"
  adressenregister:
    restart: "no"
  delta-notifier:
    restart: "no"
  op-consumer:
    restart: "no"
  dashboard:
    restart: "no"
  dashboard-login:
    restart: "no"
  #jobs-controller:
  #  restart: "no"
  #delta-producer-background-initiator:
  #  restart: "no"
  #delta-producer-pub-graph-maintainer:
  #  restart: "no"
  #delta-producer-dump-file-publisher:
  #  restart: "no"
  #publication-triplestore:
  #  restart: "no"
  #maildev:
  #  image: maildev/maildev
  #  ports:
  #    - "1080:1080"
  #deliver-email-service:
  #  environment:
  #    HOST: maildev
  #    PORT: 1025
