version: "3.4"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  ### MU-SEMTECH MANAGEMENT AND UTILITIES
  project-scripts:
    # Useful project scripts triggered using mu-cli
    image: semtech/mu-scripts:1.0.0
    volumes:
      - ./scripts/project:/app/scripts/
    restart: "no"
  ### FRONTEND
  frontend:
    image: lblod/frontend-contactgegevens-loket:1.6.0
    links:
      - identifier:backend
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
    environment:
      EMBER_ENABLE_EDIT_FEATURE: "false"
      EMBER_ANNOUNCE_MAINTENANCE_ENABLED: "false"
      EMBER_ANNOUNCE_MAINTENANCE_MESSAGE: "Het Contact- en Organisatiegegevens zal donderdag 29/05 tussen 12:00 en 15.00 u. onbeschikbaar zijn wegens onderhoud"
      EMBER_ANNOUNCE_NEW_DEPLOYMENT_ENABLED: "false"
      EMBER_ANNOUNCE_NEW_DEPLOYMENT_MESSAGE: "Het Contact- en Organisatiegegevens zal vanaf donderdag 24/03, 19.00 uur t.e.m. vrijdag 25/03 8.00 uur onbeschikbaar zijn wegens de uitrol van een nieuwe versie"
      EMBER_ANNOUNCE_TESTING_ENABLED: "true"
      EMBER_ANNOUNCE_TESTING_MESSAGE: "Het Contact- en Organisatiegegevens zal vandaag, donderdag 24/03, niet stabiel zijn wegens uitvoering van testen."
      EMBER_ENVIRONMENT_NAME: "development"
      EMBER_OAUTH_API_REDIRECT_URL: "https://contactgegevens-loket.lblod.info/authorization/callback"
      EMBER_OAUTH_API_KEY: "300a3bc4-1aba-4338-862d-05df84f084c2"
      EMBER_OAUTH_API_BASE_URL: "https://authenticatie-ti.vlaanderen.be/op/v1/auth"
      EMBER_OAUTH_API_LOGOUT_URL: "https://authenticatie-ti.vlaanderen.be/op/v1/logout"
      EMBER_OAUTH_API_SCOPE: "openid rrn profile vo abb_loketcontactapp"
      EMBER_OAUTH_SWITCH_URL: "https://contactgegevens-loket.lblod.info/switch-login"
      
  ### TRADITIONAL MU-SEMTECH STACK FOR BACKEND
  identifier:
    image: semtech/mu-identifier:1.9.1
    links:
      - dispatcher:dispatcher
    labels:
      - "logging=true"
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: '[{"variables":[],"name":"public"}]'
      DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN_HEADER: "*"
      SESSION_COOKIE_SECURE: "on"
      SESSION_COOKIE_SAME_SITE: "None"
    restart: always
    logging: *default-logging
  accountdetail:
    image: lblod/account-detail-service:0.1.0
    labels:
      - "logging=true"
    environment:
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/public"
    links:
      - database:database
    restart: always
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  database:
    image: semtech/mu-authorization:0.6.0-beta.8
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
      DATABASE_COMPATIBILITY: Virtuoso
      LOG_OUTGOING_SPARQL_QUERIES: "true"
      LOG_INCOMING_SPARQL_QUERIES: "true"
    volumes:
      - ./config/authorization:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.22.2
    links:
      - database:database
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  migrations:
    image: semtech/mu-migrations-service:0.8.0
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
  ### ACM/IDM related; login
  login:
    image: lblod/acmidm-login-service:0.9.2
    environment:
      MU_APPLICATION_AUTH_USERID_CLAIM: "vo_id"
      MU_APPLICATION_AUTH_ROLE_CLAIM: "abb_loketcontactapp_rol_3d"
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/public"
      MU_APPLICATION_AUTH_DISCOVERY_URL: "https://authenticatie-ti.vlaanderen.be/op"
      MU_APPLICATION_AUTH_CLIENT_ID: "300a3bc4-1aba-4338-862d-05df84f084c2"
      MU_APPLICATION_AUTH_REDIRECT_URI: "https://contactgegevens-loket.lblod.info/authorization/callback"
      MU_APPLICATION_AUTH_CLIENT_SECRET: "secret"
  ### ADDRESS SEARCH (not dependant on other microservices)
  adressenregister:
    image: lblod/adressenregister-fuzzy-search-service:0.8.0
    labels:
      - "logging=true"
    restart: always
  # Delta notifier
  delta-notifier:
    # Kind of delta message multiplexer
    image: semtech/mu-delta-notifier:0.2.0
    volumes:
      - ./config/delta:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  ### SYNC OP -> CLB
  op-consumer:
    image: lblod/delta-consumer:latest
    environment:
      DCR_SYNC_BASE_URL: "https://organisaties.abb.lblod.info/"
      DCR_SERVICE_NAME: "op-consumer"
      DCR_SYNC_FILES_PATH: "/sync/organizations-public-info/files"
      DCR_SYNC_DATASET_SUBJECT: "http://data.lblod.info/datasets/delta-producer/dumps/OrganizationsPublicInfoCacheGraphDump"
      DCR_INITIAL_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/op"
      DCR_DELTA_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/opDeltaFileSyncing"
      DCR_JOB_CREATOR_URI: "http://data.lblod.info/services/id/op-consumer"
      DCR_KEEP_DELTA_FILES: "true"
      DCR_DELTA_FILE_FOLDER: "/consumer-files"
      DCR_DISABLE_DELTA_INGEST: "false"
      DCR_ENABLE_DELTA_CONTEXT: "true"
      DCR_BATCH_SIZE: 1000
      SLEEP_BETWEEN_BATCHES: 100
      BYPASS_MU_AUTH_FOR_EXPENSIVE_QUERIES: "true"
      INGEST_GRAPH: "http://mu.semte.ch/graphs/ingest"

    volumes:
      - ./config/consumer/op:/config/triples-dispatching/custom-dispatching
      - ./data/files/consumer-files/op:/consumer-files/
    links:
      - virtuoso:database
    restart: always
    logging: *default-logging
  reasoner:
    image: eyereasoner/reasoning-service:increased-stack-limit
    volumes:
      - ./config/reasoner:/config
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  ### JOBS & TASKS
  jobs-controller:
    # Status indicator
    image: lblod/job-controller-service:1.0.1
    links:
      - database:database
    volumes:
      - ./config/jobs-controller/:/config/
  delta-producer-background-initiator:
    # CRON Machine to start healing, dump file, init pub graph sync
    image: lblod/delta-producer-background-jobs-initiator:1.0.1
    volumes:
      - ./config/delta-producer/background-job-initiator/config.json:/config/config.json
    labels:
      - "logging=true"
    links:
      - database:database
    restart: always
    logging: *default-logging
  # Delta producer for contact data
  delta-producer-pub-graph-maintainer:
    image: lblod/delta-producer-publication-graph-maintainer:1.0.8
    environment:
      MAX_BODY_SIZE: "50mb"
      PRETTY_PRINT_DIFF_JSON: "true"
      PUBLICATION_VIRTUOSO_ENDPOINT: "http://publication-triplestore:8890/sparql"
      PUBLICATION_MU_AUTH_ENDPOINT: "http://publication-triplestore:8890/sparql"
      SUDO_QUERY_RETRY_FOR_HTTP_STATUS_CODES: "404,500,503"
      CONFIG_SERVICES_JSON_PATH: "/config/services.json"
    volumes:
      - ./config/delta-producer/contact-data/:/config
      - ./data/files/:/share
    links:
      - database:database
      - virtuoso:virtuoso
    restart: always
    logging: *default-logging
  delta-producer-dump-file-publisher:
    # Makes giant TTL file. How invoked?
    image: lblod/delta-producer-dump-file-publisher:0.10.3
    volumes:
      - ./config/delta-producer/dump-file-publisher:/config
      - ./data/files:/share
    links:
      - database:database
    restart: always
    logging: *default-logging
  publication-triplestore:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1 # old: redpencil/virtuoso:1.2.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/publication-triplestore:/data
      - ./config/publication-triplestore/virtuoso.ini:/data/virtuoso.ini
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  # ### JOBS DASBOARD
  dashboard-login:
    image: semtech/mu-login-service:2.9.1
    links:
      - database:database
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  dashboard:
    image: lblod/frontend-dashboard:1.6.0
    labels:
      - "logging=true"
    # The following links statement shouldn't be 
    # required. But due to legacy reasons (it's using an old version of the docker-ember)
    # the container exits when the link is not set.
    links:
      - identifier:backend
    logging: *default-logging
    restart: always
  file:
    image: semtech/mu-file-service:3.2.0
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
    links:
      - database:database
    restart: always
    logging: *default-logging
  deliver-email-service:
    image: redpencil/deliver-email-service:0.2.0
    environment:
      MAILBOX_URI: 'http://data.lblod.info/id/mailboxes/1'
      WELL_KNOWN_SERVICE: ""
      EMAIL_CRON_PATTERN: '* * * * *'
    labels:
      - "logging=true"
    restart: always
    volumes:
      - ./data/files:/share
    logging: *default-logging
    links:
      - database:database
  email-service:
    image: lblod/data-validation-email-notifcation-service:latest
    environment:
      URL: "https://contactgegevens.lokaalbestuur.vlaanderen.be"
      CRON_JOB: "* * * * *"
      
    ports:
      - 1234:80
    links:
      - database:database
