version: "3.4"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  frontend:
    image: lblod/frontend-contactgegevens-loket:1.1.0
    links:
      - identifier:backend
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  identifier:
    image: semtech/mu-identifier:1.9.1
    links:
      - dispatcher:dispatcher
    labels:
      - "logging=true"
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: '[{"variables":[],"name":"public"}]'
      DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN_HEADER: "*"
      SESSION_COOKIE_SECURE: "on"
      SESSION_COOKIE_SAME_SITE: "None"
    restart: always
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  database:
    image: semtech/mu-authorization:0.6.0-beta.5
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
      DATABASE_COMPATIBILITY: Virtuoso
      LOG_OUTGOING_SPARQL_QUERIES: "true"
      LOG_INCOMING_SPARQL_QUERIES: "true"
    volumes:
      - ./config/authorization:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.22.2
    links:
      - database:database
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  migrations:
    image: semtech/mu-migrations-service:0.8.0
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
  adressenregister:
    image: lblod/adressenregister-fuzzy-search-service:0.6.3
    labels:
      - "logging=true"
    restart: always
  op-consumer:
    image: lblod/delta-consumer:0.0.24
    environment:
      DCR_SYNC_BASE_URL: "https://organisaties.abb.lblod.info"
      DCR_SERVICE_NAME: "op-consumer"
      DCR_SYNC_FILES_PATH: "/sync/organizations-public-info/files"
      DCR_SYNC_DATASET_SUBJECT: "http://data.lblod.info/datasets/delta-producer/dumps/OrganizationsPublicInfoCacheGraphDump"
      DCR_INITIAL_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/op"
      DCR_DELTA_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/opDeltaFileSyncing"
      DCR_JOB_CREATOR_URI: "http://data.lblod.info/services/id/op-consumer"
      DCR_KEEP_DELTA_FILES: "true"
      DCR_DELTA_FILE_FOLDER: "/consumer-files"
      DCR_DISABLE_DELTA_INGEST: "false"
      DCR_ENABLE_DELTA_CONTEXT: "true"
      BYPASS_MU_AUTH_FOR_EXPENSIVE_QUERIES: "true"
      INGEST_GRAPH: "http://mu.semte.ch/graphs/ingest"
    volumes:
      - ./config/consumer/op:/config/triples-dispatching/custom-dispatching
      - ./data/files/consumer-files/op:/consumer-files/
    links:
      - virtuoso:database
    restart: always
    logging: *default-logging
  # ---
  # Producer mechanism. Send contact data to OP.
  # ---
  jobs-controller:
    image: lblod/job-controller-service:1.0.1
    links:
      - db:database
    volumes:
      - ./config/jobs-controller/:/config/
  delta-producer-background-initiator:
    image: lblod/delta-producer-background-jobs-initiator:1.0.0
    environment:
      JOBS_GRAPH: "http://mu.semte.ch/graphs/jobs"
      DUMP_FILE_CREATION_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/deltaDumpFileCreation/contactgegevens"
      INITIAL_PUBLICATION_GRAPH_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/initialPublicationGraphSyncing/contactgegevens"
      HEALING_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/healingOperation/contactgegevens"
      CRON_PATTERN_DUMP_JOB: "42 * * * *" # At minute 42 every hour
      CRON_PATTERN_HEALING_JOB: "0 0 4 * * *" # everyday at 4 AM
      START_INITIAL_SYNC: "false" # prefer to disable it now. We want to have feeling with how the DB acts.
    labels:
      - "logging=true"
    links:
      - db:database
    restart: always
    logging: *default-logging
  delta-producer-pub-graph-maintainer-organizations:
    image: lblod/delta-producer-publication-graph-maintainer:1.0.3
    environment:
      MAX_BODY_SIZE: "50mb"
      JOBS_GRAPH: "http://mu.semte.ch/graphs/jobs"
      RELATIVE_FILE_PATH: "deltas/contactgegevens"
      PUBLICATION_GRAPH: "http://redpencil.data.gift/id/deltas/producer/clb-sites"
      HEALING_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/healingOperation/contactData"
      INITIAL_PUBLICATION_GRAPH_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/initialPublicationGraphSyncing/contactData"
      QUEUE_POLL_INTERVAL: 3000
      USE_VIRTUOSO_FOR_EXPENSIVE_SELECTS: "true" # some queries are just too expensive
      SKIP_MU_AUTH_INITIAL_SYNC: "true"
      HEALING_PATCH_GRAPH_BATCH_SIZE: 500
      SERVE_DELTA_FILES: "true"
      PUBLISHER_URI: "http://data.lblod.info/services/delta-production-json-diff-file-manager/organizations"
      DELTA_INTERVAL_MS: 10000
      PRETTY_PRINT_DIFF_JSON: "true"
      ERROR_GRAPH: "http://mu.semte.ch/graphs/jobs"
    volumes:
      - ./config/delta-producer/contact-data:/config
      - ./data/files/:/share
    links:
      - db:database
      - triplestore:virtuoso
    restart: always
    logging: *default-logging
  delta-producer-dump-file-publisher:
    image: lblod/delta-producer-dump-file-publisher:0.10.3
    volumes:
      - ./config/delta-producer/dump-file-publisher:/config
      - ./data/files:/share
    links:
      - db:database
    restart: always
    logging: *default-logging
  file:
    image: semtech/mu-file-service:3.3.2
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
    links:
      - db:database
    restart: always
    logging: *default-logging
  



