version: "3.4"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  frontend:
    image: lblod/frontend-contactgegevens-loket:1.3.1
    links:
      - identifier:backend
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
    environment:
      EMBER_OAUTH_API_REDIRECT_URL: "https://contactgegevens-loket.lblod.info/authorization/callback"
      EMBER_OAUTH_API_KEY: "300a3bc4-1aba-4338-862d-05df84f084c2"
      EMBER_OAUTH_API_BASE_URL: "https://authenticatie-ti.vlaanderen.be/op/v1/auth"
      EMBER_OAUTH_API_LOGOUT_URL: "https://authenticatie-ti.vlaanderen.be/op/v1/logout"
      EMBER_OAUTH_API_SCOPE: "openid rrn profile vo abb_loketcontactapp"
      EMBER_OAUTH_SWITCH_URL: "https://contactgegevens-loket.lblod.info/switch-login"
  identifier:
    image: semtech/mu-identifier:1.9.1
    links:
      - dispatcher:dispatcher
    labels:
      - "logging=true"
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: '[{"variables":[],"name":"public"}]'
      DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN_HEADER: "*"
      SESSION_COOKIE_SECURE: "on"
      SESSION_COOKIE_SAME_SITE: "None"
    restart: always
    logging: *default-logging
  accountdetail:
    image: lblod/account-detail-service:0.1.0
    labels:
      - "logging=true"
    environment:
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/public"
    links:
      - database:database
    restart: always
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  database:
    image: semtech/mu-authorization:0.6.0-beta.5
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
      DATABASE_COMPATIBILITY: Virtuoso
      LOG_OUTGOING_SPARQL_QUERIES: "true"
      LOG_INCOMING_SPARQL_QUERIES: "true"
    volumes:
      - ./config/authorization:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.22.2
    links:
      - database:database
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  migrations:
    image: semtech/mu-migrations-service:0.8.0
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
  address-search-add-on:
    image: lblod/address-search-service:latest
    volumes:
      - ./config/address-search-add-on:/data/cache
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  op-consumer:
    image: lblod/delta-consumer:0.0.24
    environment:
      DCR_SYNC_BASE_URL: "https://organisaties.abb.lblod.info"
      DCR_SERVICE_NAME: "op-consumer"
      DCR_SYNC_FILES_PATH: "/sync/organizations-public-info/files"
      DCR_SYNC_DATASET_SUBJECT: "http://data.lblod.info/datasets/delta-producer/dumps/OrganizationsPublicInfoCacheGraphDump"
      DCR_INITIAL_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/op"
      DCR_DELTA_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/opDeltaFileSyncing"
      DCR_JOB_CREATOR_URI: "http://data.lblod.info/services/id/op-consumer"
      DCR_KEEP_DELTA_FILES: "true"
      DCR_DELTA_FILE_FOLDER: "/consumer-files"
      DCR_DISABLE_DELTA_INGEST: "false"
      DCR_ENABLE_DELTA_CONTEXT: "true"
      BYPASS_MU_AUTH_FOR_EXPENSIVE_QUERIES: "true"
      INGEST_GRAPH: "http://mu.semte.ch/graphs/ingest"
    volumes:
      - ./config/consumer/op:/config/triples-dispatching/custom-dispatching
      - ./data/files/consumer-files/op:/consumer-files/
    links:
      - virtuoso:database
    restart: always
    logging: *default-logging
  login:
    image: lblod/acmidm-login-service:0.9.2
    environment:
      MU_APPLICATION_AUTH_USERID_CLAIM: "vo_id"
      MU_APPLICATION_AUTH_ROLE_CLAIM: "abb_loketcontactapp_rol_3d"
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/public"
      MU_APPLICATION_AUTH_DISCOVERY_URL: "https://authenticatie-ti.vlaanderen.be/op"
      MU_APPLICATION_AUTH_CLIENT_ID: "300a3bc4-1aba-4338-862d-05df84f084c2"
      MU_APPLICATION_AUTH_REDIRECT_URI: "https://contactgegevens-loket.lblod.info/authorization/callback"
      MU_APPLICATION_AUTH_CLIENT_SECRET: "secret"
  reasoner:
    image: eyereasoner/reasoning-service:increased-stack-limit
    volumes:
      - ./config/reasoner:/config
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
