PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX lblodgeneriek: <https://data.lblod.info/vocabularies/generiek/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX code: <http://lblod.data.gift/vocabularies/organisatie/>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>
PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/>
PREFIX organisatie: <https://data.vlaanderen.be/ns/organisatie#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
DELETE {
GRAPH ?g {
  ?a <http://data.lblod.info/id/gestructureerdeIdentificator/gestructureerdeIdentificator> ?b.
}
}
INSERT {
GRAPH ?g {
  ?a generiek:gestructureerdeIdentificator ?b.
}

}
WHERE {
GRAPH ?g {
  ?a <http://data.lblod.info/id/gestructureerdeIdentificator/gestructureerdeIdentificator> ?b.
}
}

DELETE {
GRAPH ?g {
  ?a a <http://data.lblod.info/id/gestructureerdeIdentificator/GestructureerdeIdentificator>.
}
}
INSERT {
GRAPH ?g {
  ?a a generiek:GestructureerdeIdentificator.
}

}
WHERE {
GRAPH ?g {
  ?a a <http://data.lblod.info/id/gestructureerdeIdentificator/GestructureerdeIdentificator>.
}
}

DELETE {
GRAPH ?g {
  ?a <http://data.lblod.info/id/gestructureerdeIdentificator/lokaleIdentificator> ?b.
}
}
INSERT {
GRAPH ?g {
  ?a generiek:lokaleIdentificator ?b.
}

}
WHERE {
GRAPH ?g {
  ?a <http://data.lblod.info/id/gestructureerdeIdentificator/lokaleIdentificator> ?b.
}
}