PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX lblodgeneriek: <https://data.lblod.info/vocabularies/generiek/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX code: <http://lblod.data.gift/vocabularies/organisatie/>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>
PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/>
PREFIX organisatie: <https://data.vlaanderen.be/ns/organisatie#>
PREFIX schema: <http://schema.org/>
PREFIX locn: <http://www.w3.org/ns/locn#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
DELETE {
GRAPH <http://mu.semte.ch/application> {
  ?contactPoint a schema:ContactPoint;
    mu:uuid ?uuid;
    schema:email ?email;
    schema:telephone ?telephone;
    schema:faxNumber ?fax;
    foaf:page ?website;
    schema:contactType ?type;
    locn:address ?address.
}
}
INSERT {
GRAPH ?g {
  ?contactPoint a schema:ContactPoint;
    mu:uuid ?uuid;
    schema:email ?email;
    schema:telephone ?telephone;
    schema:faxNumber ?fax;
    foaf:page ?website;
    schema:contactType ?type;
    locn:address ?address.
}

}
WHERE {
GRAPH ?g {
  ?site org:siteAddress ?contactPoint.
}
?contactPoint a schema:ContactPoint;
  mu:uuid ?uuid.
  OPTIONAL {
    ?contactPoint schema:email ?email.
  }
  OPTIONAL {
    ?contactPoint schema:telephone ?telephone.
  }
  OPTIONAL {
    ?contactPoint schema:faxNumber ?fax.
  }
  OPTIONAL {
    ?contactPoint foaf:page ?website.
  }
  OPTIONAL {
    ?contactPoint schema:contactType ?type.
  }
  OPTIONAL {
    ?contactPoint locn:address ?address.
  }
}