PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/>
DELETE {
    GRAPH ?g {
        ?site ere:vestigingstype <http://lblod.data.gift/concepts/fbec5e94aba343b0a7361aca8a0c7d79>.
    }
}INSERT {
    GRAPH ?g {
        ?site ere:vestigingstype <http://lblod.data.gift/concepts/dcc01338-842c-4fbd-ba68-3ca6f3af975c>.
    }
}WHERE {
    GRAPH ?g {
        ?site ere:vestigingstype <http://lblod.data.gift/concepts/fbec5e94aba343b0a7361aca8a0c7d79>.
    }
}