PREFIX dct: <http://purl.org/dc/terms/>

DELETE {
  GRAPH ?g {
    ?subject dct:modified ?modified .
  }
}
INSERT {
  GRAPH ?g {
    ?subject dct:modified "2023-12-01T12:30:00-05:00"^^xsd:dateTime .
  }
}
WHERE {
  GRAPH ?g {
    ?subject dct:modified ?modified .
  }
  VALUES ?subject {
    <http://data.lblod.info/id/vestigingen/632748A0A73E5BA58C949DEF> 
    <http://data.lblod.info/id/vestigingen/f3289063f975da9e061e4a20dea5b568> 
    <http://data.lblod.info/id/vestigingen/e215e097cd2f054c9de6db80cf34d65d> 
    <http://data.lblod.info/id/vestigingen/6671A6AF541239A5EC5CDC4B>
    <http://data.lblod.info/id/vestigingen/64FEBFD45BFBFB1ED9EA9300>
    <http://data.lblod.info/id/vestigingen/632747BEA73E5BA58C949DEB>
  }
}